import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const KNOWLEDGE_DIR = join(import.meta.dirname, "..", "knowledge");
const OUTPUT_FILE = join(import.meta.dirname, "..", "lib", "knowledge", "generated.ts");

const EXPECTED_TOPIC_IDS = [
  "about-cadre",
  "services",
  "industries",
  "ai-maturity-index",
  "llm-selection",
  "security",
  "portal",
  "getting-started",
  "pricing",
] as const;

function parseTopic(fileName: string, raw: string) {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const titleLine = lines.find((line) => line.startsWith("# "));
  if (!titleLine) {
    throw new Error(`${fileName}: missing an "# " H1 title line`);
  }
  const title = titleLine.slice(2).trim();
  const content = lines.filter((line) => line !== titleLine).join("\n").trim();
  return { title, content };
}

function main() {
  const fileNames = readdirSync(KNOWLEDGE_DIR).filter((name) => name.endsWith(".md"));
  const foundTopicIds = fileNames.map((name) => name.replace(/\.md$/, "")).sort();
  const expectedSorted = [...EXPECTED_TOPIC_IDS].sort();

  if (JSON.stringify(foundTopicIds) !== JSON.stringify(expectedSorted)) {
    throw new Error(
      `knowledge/*.md does not match the expected TopicId set.\n` +
        `Expected: ${expectedSorted.join(", ")}\n` +
        `Found:    ${foundTopicIds.join(", ")}`,
    );
  }

  const entries = EXPECTED_TOPIC_IDS.map((topicId) => {
    const fileName = `${topicId}.md`;
    const raw = readFileSync(join(KNOWLEDGE_DIR, fileName), "utf-8");
    const { title, content } = parseTopic(fileName, raw);
    return { topicId, title, content };
  });

  const body = entries
    .map(
      ({ topicId, title, content }) =>
        `  "${topicId}": {\n    title: ${JSON.stringify(title)},\n    content: ${JSON.stringify(content)},\n  },`,
    )
    .join("\n");

  const output = `// Generated by scripts/build-knowledge.ts from knowledge/*.md — do not edit by hand.
// Run \`npm run build:knowledge\` after changing any knowledge/*.md file.

export type TopicId =
${EXPECTED_TOPIC_IDS.map((id) => `  | "${id}"`).join("\n")};

export const KNOWLEDGE_TOPICS: Record<TopicId, { title: string; content: string }> = {
${body}
};
`;

  mkdirSync(join(import.meta.dirname, "..", "lib", "knowledge"), { recursive: true });
  writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Wrote ${entries.length} topics to lib/knowledge/generated.ts`);
}

main();
